version: '2'
services: 
  redis: 
    image: redis:latest
    hostname: redis
    ports:
      - 6379:6379
  commander:
    image: rediscommander/redis-commander:latest
    hostname: redis-commander
    environment:
      - REDIS_HOSTS=local:redis:6379
    ports:
      - "8081:8081"